os: osx
matrix:
  include:
  - osx_image: xcode9	
  - osx_image: xcode8.3	
  - osx_image: xcode8.2	
  - osx_image: xcode8.1	
  - osx_image: xcode8	
  - osx_image: xcode7.3 
  - osx_image: xcode6.4	
language: java
script: java -version
